### ISSUE TITLE
The link in demo is broken

### ISSUE THREAD

**Issue by egoist** [IonicaBizau/mini-lightbox#11]
https://github.com/IonicaBizau/mini-lightbox/blob/gh-pages/index.html#L11

it should be:

```html
https://rawgit.com/IonicaBizau/mini-lightbox/gh-pages/lib/mini-lightbox.js
```

**Comment by IonicaBizau** [comment]
@egoist Thanks for head's up! Fixed the path to use the local `lib` file that is minified. :four_leaf_clover:

**Comment by egoist** [comment]
nice, the demo works perfectly now 👍

**Comment by IonicaBizau** [comment]
Thanks! Glad to hear. :grin:
