### ISSUE TITLE
Missing browser support information

### ISSUE THREAD

**Issue by miduga** [IonicaBizau/mini-lightbox#13]
Great work. It would be great to have some browser support information for that library.

**Comment by IonicaBizau** [comment]
This uses CSS3 animations. Probably on older browsers the animations won't work.

http://caniuse.com/#feat=css-transitions

Contributions adding this to docs would be welcome! :memo:

**Comment by miduga** [comment]
Blazing fast response. I appreciate it. 👍 I'm going to use it in a project and I'll be back to you if I found any problems regarding browser support. Thanks!

**Comment by IonicaBizau** [comment]
@miduga Great! ✨  If you see any way to improve the functionality, feel free to contribute. I wrote this code few years ago. 😁
