### ISSUE TITLE
Indentation in README

### ISSUE THREAD

**Issue by Fajkowsky** [IonicaBizau/mini-lightbox#6]
There is wrong indentation in README file for code section.

**Comment by IonicaBizau** [comment]
@Fajkowsky Thanks for pointing this out!

Since the README.md file is generated, we should update the [`package.json`](https://github.com/IonicaBizau/mini-lightbox/blob/aea393d8890a3b6ef3437aeb90e5fd5a4661bb34/package.json#L32) file as well. Can you do that?

**Comment by Fajkowsky** [comment]
Yes, sure. I will do this today.

**Comment by IonicaBizau** [comment]
Fixed in #10. :ship: **`2.0.0`** :tada:
